# Generated by Django 3.2 on 2023-01-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_auto_20230117_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comprador',
        ),
    ]
