# Generated by Django 3.2 on 2023-01-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_delete_comprador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='price',
        ),
    ]
