# Generated by Django 3.2 on 2023-01-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_remove_curso_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='curso',
            name='image',
            field=models.ImageField(blank=True, default='/curso.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='episodio',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
