export const CURSO_LIST_REQUEST = 'CURSO_LIST_REQUEST'
export const CURSO_LIST_SUCCESS = 'CURSO_LIST_SUCCESS'
export const CURSO_LIST_FAIL = 'CURSO_LIST_FAIL'

export const CURSO_LAST_REQUEST = 'CURSO_LAST_REQUEST'
export const CURSO_LAST_SUCCESS = 'CURSO_LAST_SUCCESS'
export const CURSO_LAST_FAIL = 'CURSO_LAST_FAIL'

export const CURSO_DETAILS_REQUEST = 'CURSO_DETAILS_REQUEST'
export const CURSO_DETAILS_SUCCESS = 'CURSO_DETAILS_SUCCESS'
export const CURSO_DETAILS_FAIL = 'CURSO_DETAILS_FAIL'

export const CURSO_CREATE_REVIEW_REQUEST = 'CURSO_CREATE_REVIEW_REQUEST'
export const CURSO_CREATE_REVIEW_SUCCESS = 'CURSO_CREATE_REVIEW_SUCCESS'
export const CURSO_CREATE_REVIEW_FAIL = 'CURSO_CREATE_REVIEW_FAIL'
export const CURSO_CREATE_REVIEW_RESET = 'CURSO_CREATE_REVIEW_RESET'

export const EPISODIO_DETAILS_REQUEST = 'EPISODIO_DETAILS_REQUEST';
export const EPISODIO_DETAILS_SUCCESS = 'EPISODIO_DETAILS_SUCCESS';
export const EPISODIO_DETAILS_FAIL = 'EPISODIO_DETAILS_FAIL';

export const EPISODIO_CREATE_COMMENT_REQUEST = 'EPISODIO_CREATE_COMMENT_REQUEST'
export const EPISODIO_CREATE_COMMENT_SUCCESS = 'EPISODIO_CREATE_COMMENT_SUCCESS'
export const EPISODIO_CREATE_COMMENT_FAIL = 'EPISODIO_CREATE_COMMENT_FAIL'
export const EPISODIO_CREATE_COMMENT_RESET = 'EPISODIO_CREATE_COMMENT_RESET'

export const EPISODIO_ALL_REQUEST = 'EPISODIO_ALL_REQUEST'
export const EPISODIO_ALL_SUCCESS = 'EPISODIO_ALL_SUCCESS'
export const EPISODIO_ALL_FAIL = 'EPISODIO_ALL_FAIL'










